/** Permission constants — đồng bộ với BE */
export const PERMISSIONS = {
  // Departments
  DEPARTMENT_VIEW: 'DEPARTMENT_VIEW',
  DEPARTMENT_MANAGE: 'DEPARTMENT_MANAGE',
  // Users/Personnel (BE dùng USER_*)
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  // Aliases for backward compatibility
  PERSONNEL_VIEW: 'USER_VIEW',
  PERSONNEL_CREATE: 'USER_CREATE',
  PERSONNEL_UPDATE: 'USER_UPDATE',
  PERSONNEL_DELETE: 'USER_DELETE',
  PERSONNEL_RESET_PASSWORD: 'PERSONNEL_RESET_PASSWORD',
  PERSONNEL_LOCK: 'PERSONNEL_LOCK',
  // Roles/System Config (BE dùng ROLE_*)
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE',
  // Aliases
  CONFIG_VIEW: 'ROLE_VIEW',
  CONFIG_UPDATE: 'ROLE_MANAGE',
  // Applications
  APPLICATION_VIEW: 'APPLICATION_VIEW',
  APPLICATION_CREATE: 'APPLICATION_CREATE',
  APPLICATION_SUBMIT: 'APPLICATION_SUBMIT',
  APPLICATION_APPROVE: 'APPLICATION_APPROVE',
  APPLICATION_REJECT: 'APPLICATION_REJECT',
  APPLICATION_CANCEL: 'APPLICATION_CANCEL',
  APPLICATION_DELETE: 'APPLICATION_DELETE',
  WILDCARD: '*',
} as const;
export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Role names (từ BE enum)
export const ROLES = {
  ADMIN: 'ADMIN',
  HR: 'HR',
  MANAGER: 'MANAGER',
  TEAM_LEADER: 'TEAM_LEADER',
  STAFF: 'STAFF',
} as const;
